[package]
name = "tockenized-rewards"
version = "1.0.0"
authors = []

[addresses]
MyModule =  "0x77dcd25d1dad82ed47f3dc3105776cbb81a7b65b3b2d75fa5c8b48a380fd0af6"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
