[package]
name = "tockenized-rewards"
version = "1.0.0"
authors = []

[addresses]
MyModule =  "0x3543a21a5743405a49210fd230b74f6ab2c962e89b3d9a7b019e168f0256825a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
